system:
  name: adsbcot
  repo: https://github.com/bryanjonas/adsbcot

external-services:
  adsb:
    type: network
    port: 30002
  tak:
    type: network
    port: 8087

outputs:
  cot:
    type: cot
    stimulus:
      service: adsb
      type: inject
      file:
          - 'inputs/adsb.txt'
      origin: adsb
    recipient: 
      service: tak
      type: recieve
      file: 
          - 'outputs/cot1.xml'
          - 'outputs/cot2.xml'

